blueprint:
  name: To-do - Add unique item
  description: >
    Add an item to a to-do list if the item does not already exist, or if it exists but is completed, it will be marked as needs action again.


    The item name is compared to the existing items in the list.


    This blueprint is a simple distribution wrapper around a generic script.

    Just press save to create one script you can use on any to-do list.

    Use the single script created in any automations, input fields allow you to customise it for your automation.
  author: andrew-codechimp
  source_url: https://github.com/andrew-codechimp/HA-Blueprints/blob/main/scripts/todo_add_unique_item.yaml
  domain: script

sequence:
  - target:
      entity_id: '{{ list }}'
    data:
      status: needs_action
    response_variable: mylistneedsaction
    action: todo.get_items
  - target:
      entity_id: '{{ list }}'
    data:
      status: completed
    response_variable: mylistcompleted
    action: todo.get_items
  - if:
      - condition: template
        value_template: |
          {{
            mylistcompleted[list]['items']
            | selectattr('summary', 'search', item)
            | list
            | count == 0
          }}
    then:
      - if:
          - condition: template
            value_template: |
              {{
                state_attr(list, 'supported_features') is not none
                and (state_attr(list, 'supported_features') | int(0)) | bitwise_and(8)
              }}
        then:
          - action: todo.update_item
            target:
              entity_id: '{{ list }}'
            data:
              item: '{{ item }}'
              status: needs_action
              description: '{{ description | default("") }}'
        else:
          - action: todo.update_item
            target:
              entity_id: '{{ list }}'
            data:
              item: '{{ item }}'
              status: needs_action
    else:
      - if:
          - condition: template
            value_template: |
              {{
                mylistneedsaction[list]['items']
                | selectattr('summary', 'search', item)
                | list
                | count == 0
              }}
        then:
          - if:
              - condition: template
                value_template: |
                  {{
                    state_attr(list, 'supported_features') is not none
                    and (state_attr(list, 'supported_features') | int(0)) | bitwise_and(8)
                  }}
            then:
              - action: todo.add_item
                target:
                  entity_id: '{{ list }}'
                data:
                  item: '{{ item }}'
                  description: '{{ description | default("") }}'
            else:
              - action: todo.add_item
                target:
                  entity_id: '{{ list }}'
                data:
                  item: '{{ item }}'
fields:
  item:
    name: Item
    description: The to-do item to add, if the item already exists in the list it will not be added again, if it exists but is completed it will be marked as needs action again.
    required: true
    selector:
      text: null
  description:
    selector:
      text:
        multiple: false
        multiline: true
    name: Description
    description: An optional description. Note that not all to-do lists support descriptions.
  list:
    name: List
    description: The to-do list to add the item to.
    required: true
    selector:
      entity:
        filter:
          - domain: todo

icon: mdi:format-list-checks
mode: queued
